---
data:
  container_name: gitserver-data
  image: derektamsen/gitserver-data
  volumes:
    - /data
  mem_limit: 512m
  cpu_shares: 512

app:
  container_name: gitserver
  image: derektamsen/gitserver
  mem_limit: 512m
  cpu_shares: 512
  read_only: true
  restart: on-failure:5
  ports:
    - "2222:22"
  volumes_from:
    - data
  environment:
    - SSH_KEY="${GITSERVER_SSH_KEY}"
    - SSH_ADMIN="${GITSERVER_SSH_ADMIN}"
